baseURL = 'https://luizfelipeoliver.github.io/my_blog/'
languageCode = 'pt-br' 
title = 'Luiz Dev'
theme = 're-terminal'
paginate = 5

[params]
  
  themeColor = "blue"

  [languages.en.params.logo]
      logoText = "luiz dev"
